spring:
  application:
    name: credit-sussie-media-application

server:
  port: 8080

info:
  app:
    name: credit-sussie-media-application
    description: credit-sussie-media-application
    version: @project.version@

management:
  security:
    enabled: false
  port: 9000
